#!/usr/bin/env bash
# crswd installer — one command, no clone, no compiler.
#
#   curl -fsSL https://raw.githubusercontent.com/nctiggy/claude-remote-session-webhook/main/install.sh | bash
#
# It downloads a published release and proves the bytes are the ones this
# project published, before any of them can be run. Two checks, in this order:
#
#   1. ed25519 over SHA256SUMS, against a key carried in this file
#   2. sha256 of the downloaded tarball, against its line in SHA256SUMS
#
# The order is the point. A checksum file travels with the artifacts it
# describes, so on its own it proves only that the two arrived together —
# anyone able to serve a tampered tarball can serve a checksum that matches it.
# The signature is what says the list came from this project, and a release
# without one is refused rather than installed unverified: refusing costs an
# install, and the other way costs the host.
#
# Unpacking is the first moment anything here is executable, because tar
# restores the mode stored in the archive. Both checks stand in front of it.
#
# This script belongs to the project rather than to a person: no home
# directory and no username appears below. The account name in the URLs is
# where the bytes are published, and there is nowhere else to fetch them from.
set -eu

# One base URL, so a fork changes a single line.
readonly REPO_URL="https://github.com/nctiggy/claude-remote-session-webhook"

# What the release workflow builds, and all it builds. Anything else is refused
# by name rather than handed an amd64 binary to fail on later.
readonly PUBLISHED="linux/amd64 linux/arm64"

say() { printf 'crswd: %s\n' "$*"; }
die() {
  printf 'crswd: %s\n' "$*" >&2
  exit 1
}

# The ed25519 public keys a release may be signed by, one base64 line each —
# the same lines as internal/updater/release_key.txt, which the daemon embeds
# for the same purpose. Verification succeeds against any of them, so rotation
# is additive: add the new line, and drop the old one only once every release
# still worth installing is signed by the new key.
#
# It is empty until the operator runs `crswd keygen`, keeps the private half in
# the repository secret RELEASE_SIGNING_KEY, and commits the public half here.
# Until then this installer refuses every release, which is the intended
# failure and not an oversight: a key generated by anything other than the
# person who is supposed to hold it proves nothing about who signed a release.
release_keys() {
  cat <<'RELEASE_KEYS'
RELEASE_KEYS
}

require_tools() {
  missing=""
  for tool in curl tar sha256sum openssl; do
    command -v "$tool" > /dev/null 2>&1 || missing="$missing $tool"
  done
  [ -z "$missing" ] || die "not on PATH:$missing"
}

unsupported() {
  printf 'crswd: no release is published for %s/%s\n' "$1" "$2" >&2
  printf 'crswd: published: %s\n' "${PUBLISHED// /, }" >&2
  exit 1
}

# Sets os and arch, or refuses naming what is published. Downloading the amd64
# tarball onto an arm host produces a file that cannot exec, discovered by
# systemd long after the install said it worked.
detect_platform() {
  os=$(uname -s)
  machine=$(uname -m)
  case "$os" in
    Linux) os=linux ;;
    *) unsupported "$os" "$machine" ;;
  esac
  case "$machine" in
    x86_64 | amd64) arch=amd64 ;;
    aarch64 | arm64) arch=arm64 ;;
    *) unsupported "$os" "$machine" ;;
  esac
}

# The tag the `latest` pointer resolves to, read from the redirect rather than
# from the API: an unauthenticated API call is rate-limited by address, so an
# office behind one address installs a few times and then cannot.
resolve_version() {
  local url
  url=$(curl -fsSL -o /dev/null -w '%{url_effective}' "$REPO_URL/releases/latest") ||
    die "could not reach $REPO_URL/releases/latest"
  version=${url##*/}
  case "$version" in
    v[0-9]*) ;;
    *) die "no release is published yet ($url)" ;;
  esac
}

fetch() {
  local url="$REPO_URL/releases/download/$version/$1"
  curl -fsSL -o "$workdir/$1" "$url" || die "could not fetch $1 from $url — refusing"
}

verify_signature() {
  local key pem found
  pem="$workdir/release_key.pem"
  found=""

  [ -s SHA256SUMS.sig ] || die "the $version release carries an empty SHA256SUMS.sig — refusing"

  while IFS= read -r key; do
    case "$key" in '' | \#*) continue ;; esac
    found=yes
    # A raw ed25519 public key wrapped as SubjectPublicKeyInfo, which is the
    # only shape openssl(1) will read. The 12-byte DER header is constant, and
    # 12 divides by three, so its base64 concatenates cleanly with the key's.
    printf -- '-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA%s\n-----END PUBLIC KEY-----\n' "$key" > "$pem"
    if openssl pkeyutl -verify -pubin -inkey "$pem" -rawin \
      -in SHA256SUMS -sigfile SHA256SUMS.sig > /dev/null 2>&1; then
      rm -f -- "$pem"
      say "verifying SHA256SUMS.sig ... ok"
      return 0
    fi
  done <<EOF
$(release_keys)
EOF

  rm -f -- "$pem"
  [ -n "$found" ] || die "this installer carries no release key, so nothing it downloads can be shown to come from this project — refusing"
  die "SHA256SUMS is not signed by any key this installer carries — refusing"
}

verify_checksum() {
  # The published line for this one asset, matched whole. `sha256sum -c` over
  # the file itself would fail against a release that is entirely correct:
  # SHA256SUMS covers every asset and only one of them was downloaded.
  if ! grep -Fqx -- "$(sha256sum "$1")" SHA256SUMS; then
    grep -Fq -- "  $1" SHA256SUMS || die "SHA256SUMS names no $1 — refusing"
    die "$1 does not match its published checksum — refusing"
  fi
  say "verifying $1 ... ok"
}

main() {
  require_tools
  detect_platform
  say "detected $os/$arch"

  resolve_version
  say "downloading $version"

  workdir=$(mktemp -d)
  trap 'rm -rf -- "$workdir"' EXIT

  tarball="crswd_${version}_linux_${arch}.tar.gz"
  fetch "$tarball"
  fetch SHA256SUMS
  # Not optional. A release with no signature is refused, never installed on
  # the strength of a checksum that arrived from the same place as the bytes.
  fetch SHA256SUMS.sig

  cd "$workdir"
  verify_signature
  verify_checksum "$tarball"

  # Only the member the release publishes, by name: an archive carrying extra
  # paths then cannot write anywhere this did not intend.
  mkdir -p unpacked
  tar -xzf "$tarball" -C unpacked crswd
  say "unpacked $tarball"
}

main "$@"
