#!/usr/bin/env bash
# crswd installer — one command, no clone, no compiler.
#
#   curl -fsSL https://raw.githubusercontent.com/nctiggy/claude-remote-session-webhook/main/install.sh | bash
#
# It downloads a published release and proves the bytes are the ones this
# project published, before any of them can be run. Two checks, in this order:
#
#   1. ed25519 over SHA256SUMS, against a key carried in this file
#   2. sha256 of each downloaded asset, against its line in SHA256SUMS
#
# The order is the point. A checksum file travels with the artifacts it
# describes, so on its own it proves only that the two arrived together —
# anyone able to serve a tampered tarball can serve a checksum that matches it.
# The signature is what says the list came from this project, and a release
# without one is refused rather than installed unverified: refusing costs an
# install, and the other way costs the host.
#
# Unpacking is the first moment anything here is executable, because tar
# restores the mode stored in the archive. Both checks stand in front of it.
#
# What it then writes is the binary, the service unit, a record of the unit it
# wrote, a configuration file, and the one directory that configuration lets a
# session run in — but it replaces neither a configuration nor a unit it cannot
# show it wrote itself, so running it again on a host somebody has since
# configured is safe. It enables nothing and starts nothing: enabling a unit is
# a decision about the machine it runs on, and this script is a stranger there.
#
# This script belongs to the project rather than to a person: no home
# directory and no username appears below. The account name in the URLs is
# where the bytes are published, and there is nowhere else to fetch them from.
set -eu

# One base URL, so a fork changes a single line.
readonly REPO_URL="https://github.com/nctiggy/claude-remote-session-webhook"

# What the release workflow builds, and all it builds. Anything else is refused
# by name rather than handed an amd64 binary to fail on later.
readonly PUBLISHED="linux/amd64 linux/arm64"

# The published unit, downloaded and checked like everything else. It is written
# into ~/.config/systemd/user, where systemd runs what it says — an asset taken
# on trust there is the same problem as an unverified binary under another name.
readonly UNIT_ASSET="crswd.service"

# Everything this installer writes, and the only places it writes. Each is
# spelled once, relative to $HOME, so the path it creates and the `~/…` it
# prints cannot drift — and so no home directory is named in this file.
readonly BINARY=".local/bin/crswd"
readonly UNIT=".config/systemd/user/crswd.service"
readonly UNIT_RECORD=".local/share/crswd/crswd.service.sha256"
readonly CONFIG=".config/crswd/config"

# The one directory a session may run in, created beside a new configuration
# and named by it. `code` is the daemon's own default, spelled the same way in
# internal/config and in config.example. $HOME itself is never it: SSH keys,
# cloud credentials and browser profiles all live directly under $HOME, and an
# allowlist containing them contains everything, which is no allowlist.
readonly ROOT="code"

say() { printf 'crswd: %s\n' "$*"; }
die() {
  printf 'crswd: %s\n' "$*" >&2
  exit 1
}

# The ed25519 public keys a release may be signed by, one base64 line each —
# the same lines as internal/updater/release_key.txt, which the daemon embeds
# for the same purpose. Verification succeeds against any of them, so rotation
# is additive: add the new line, and drop the old one only once every release
# still worth installing is signed by the new key.
#
# An empty list refuses every release rather than skipping the check, which is
# the intended failure and not an oversight: a key generated by anything other
# than the person who is supposed to hold it proves nothing about who signed a
# release. To add one, run `crswd keygen`, keep the private half in the
# repository secret RELEASE_SIGNING_KEY, and commit the public half here and to
# internal/updater/release_key.txt.
release_keys() {
  cat <<'RELEASE_KEYS'
49NjabDTQvOEX7mTi/4ksAhsG/34ICzfqRe9wHZO9UY=
RELEASE_KEYS
}

require_tools() {
  missing=""
  for tool in curl tar sha256sum openssl install; do
    command -v "$tool" > /dev/null 2>&1 || missing="$missing $tool"
  done
  [ -z "$missing" ] || die "not on PATH:$missing"
}

unsupported() {
  printf 'crswd: no release is published for %s/%s\n' "$1" "$2" >&2
  printf 'crswd: published: %s\n' "${PUBLISHED// /, }" >&2
  exit 1
}

# Sets os and arch, or refuses naming what is published. Downloading the amd64
# tarball onto an arm host produces a file that cannot exec, discovered by
# systemd long after the install said it worked.
detect_platform() {
  os=$(uname -s)
  machine=$(uname -m)
  case "$os" in
    Linux) os=linux ;;
    *) unsupported "$os" "$machine" ;;
  esac
  case "$machine" in
    x86_64 | amd64) arch=amd64 ;;
    aarch64 | arm64) arch=arm64 ;;
    *) unsupported "$os" "$machine" ;;
  esac
}

# The tag the `latest` pointer resolves to, read from the redirect rather than
# from the API: an unauthenticated API call is rate-limited by address, so an
# office behind one address installs a few times and then cannot.
resolve_version() {
  local url
  url=$(curl -fsSL -o /dev/null -w '%{url_effective}' "$REPO_URL/releases/latest") ||
    die "could not reach $REPO_URL/releases/latest"
  version=${url##*/}
  case "$version" in
    v[0-9]*) ;;
    *) die "no release is published yet ($url)" ;;
  esac
}

fetch() {
  local url="$REPO_URL/releases/download/$version/$1"
  curl -fsSL -o "$workdir/$1" "$url" || die "could not fetch $1 from $url — refusing"
}

verify_signature() {
  local key pem found
  pem="$workdir/release_key.pem"
  found=""

  [ -s SHA256SUMS.sig ] || die "the $version release carries an empty SHA256SUMS.sig — refusing"

  while IFS= read -r key; do
    case "$key" in '' | \#*) continue ;; esac
    found=yes
    # A raw ed25519 public key wrapped as SubjectPublicKeyInfo, which is the
    # only shape openssl(1) will read. The 12-byte DER header is constant, and
    # 12 divides by three, so its base64 concatenates cleanly with the key's.
    printf -- '-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA%s\n-----END PUBLIC KEY-----\n' "$key" > "$pem"
    if openssl pkeyutl -verify -pubin -inkey "$pem" -rawin \
      -in SHA256SUMS -sigfile SHA256SUMS.sig > /dev/null 2>&1; then
      rm -f -- "$pem"
      say "verifying SHA256SUMS.sig ... ok"
      return 0
    fi
  done <<EOF
$(release_keys)
EOF

  rm -f -- "$pem"
  [ -n "$found" ] || die "this installer carries no release key, so nothing it downloads can be shown to come from this project — refusing"
  die "SHA256SUMS is not signed by any key this installer carries — refusing"
}

verify_checksum() {
  # The published line for this one asset, matched whole. `sha256sum -c` over
  # the file itself would fail against a release that is entirely correct:
  # SHA256SUMS covers every asset and only one of them was downloaded.
  if ! grep -Fqx -- "$(sha256sum "$1")" SHA256SUMS; then
    grep -Fq -- "  $1" SHA256SUMS || die "SHA256SUMS names no $1 — refusing"
    die "$1 does not match its published checksum — refusing"
  fi
  say "verifying $1 ... ok"
}

# place writes one verified file under $HOME at a mode it states rather than one
# it inherits. install(1) rather than cp: it unlinks the destination before
# writing, so replacing the binary of a daemon that happens to be running leaves
# a new file under the old name instead of failing with ETXTBSY.
place() {
  local mode="$1" src="$2" rel="$3"
  mkdir -p -- "$HOME/${rel%/*}"
  install -m "$mode" -- "$src" "$HOME/$rel"
  say "installed ~/$rel"
}

# The hash of the unit as it was written. It is the only thing a later run can
# use to tell a unit this installer wrote from one the operator has since
# edited, and it is written by the same step that writes the unit: a run that
# placed one and recorded nothing would leave the next run unable to tell those
# two apart, and the only safe answer to that is to refuse to touch it.
record_unit() {
  local sum
  mkdir -p -- "$HOME/${UNIT_RECORD%/*}"
  sum=$(sha256sum < "$HOME/$UNIT")
  # The digest alone, no filename: what is compared is the contents of a path
  # this installer already knows, and a `sha256sum -c` line would tie the record
  # to the directory it was taken from.
  printf '%s\n' "${sum%% *}" > "$HOME/$UNIT_RECORD"
}

# The unit, unless the copy on this host is not ours to replace. The record
# written beside the last one we wrote is the only evidence that distinguishes a
# unit this installer placed from a unit the operator authored, and a unit is
# not a document: it is what systemd executes, with which environment, and
# whether it is enabled at boot.
#
#   record matches   untouched since we wrote it     replace
#   record differs   the operator edited it          leave it, say so
#   no record        somebody else put it there      leave it, say so
#
# The third row is not an edge case and reading it as permission is the failure
# this exists to prevent: every host deployed before this installer existed has
# a hand-written unit and no record of one, including the host that publishes
# these releases. A record that is not there to be read falls in the same row —
# there is no information in one, and the safe direction is to leave a file
# alone.
#
# Nothing is recorded on the two paths that leave the unit alone. Recording
# somebody else's unit would make the *next* run read it as ours and replace it,
# which is this refusal undoing itself one command later.
place_unit() {
  local recorded current
  if [ -e "$HOME/$UNIT" ]; then
    if [ ! -f "$HOME/$UNIT_RECORD" ] || [ ! -r "$HOME/$UNIT_RECORD" ]; then
      say "~/$UNIT was not written by this installer — leaving it alone"
      return 0
    fi
    recorded=$(cat -- "$HOME/$UNIT_RECORD")
    current=$(sha256sum < "$HOME/$UNIT")
    if [ "$recorded" != "${current%% *}" ]; then
      say "~/$UNIT has been modified — leaving it alone"
      return 0
    fi
  fi

  place 0644 "$UNIT_ASSET" "$UNIT"
  record_unit
}

# The configuration, and only when there is none. The operator's file is the one
# thing on this host they authored; an installer that replaced it would destroy
# it during an operation they think of as safe.
#
# Every setting with a default still arrives commented out, so the file behaves
# as no file at all in each of them. Two cannot.
#
# The shared secret, because there is no default that could stand in for a
# credential and the daemon refuses to start without one. So it is generated
# here rather than left as a blank the operator fills in, because a required
# credential filled in by hand is a credential somebody types from memory.
#
# The allowlist, because its default is only a default where the directory
# already exists — every entry must resolve at startup, so a host without
# ~/code has a daemon that refuses to boot rather than one running on the
# built-in root. The directory is created here and then named explicitly: this
# is the whole of what bounds a session that runs with the permission prompt
# turned off, and a boundary nobody can read is a boundary nobody checks.
#
# That is also what stopped the 0600 below being a precaution. This file now is
# a credential, and the daemon refuses to read one that sets a secret at any
# other mode.
write_config() {
  local secret
  if [ -e "$HOME/$CONFIG" ]; then
    say "~/$CONFIG exists — leaving it alone"
    return 0
  fi

  # openssl is already required — it is what verifies the release signature — so
  # the CSPRNG this reaches for costs no new dependency.
  #
  # The value is never printed. It goes from this substitution into a file
  # created under a 0077 umask and nowhere else: not to say(), not into an error
  # message, not into the transcript. The installer's output is a terminal
  # scrollback, a CI log, and often the far end of a pipe from curl, so a secret
  # printed once is a secret in all three — the same reason `crswd keygen`
  # writes nothing to disk.
  secret=$(openssl rand -hex 32) || die "could not generate a shared secret"
  # 32 bytes is the minimum the daemon accepts and `-hex 32` is 64 characters.
  # A short one would be written, refused at startup, and diagnosed by whoever
  # is reading a service that will not come up.
  [ "${#secret}" -ge 64 ] || die "openssl produced a short shared secret — refusing to write one the daemon would reject"

  # Before the file that names it, and not after: an allowed_roots entry that
  # does not resolve is a startup failure, so a configuration written first
  # would be a configuration this installer knows the daemon will refuse.
  if [ -d "$HOME/$ROOT" ]; then
    say "~/$ROOT is already here — sessions will be confined to it"
  else
    mkdir -p -- "$HOME/$ROOT" ||
      die "could not create ~/$ROOT, which is the only directory sessions would be allowed to run in"
    say "created ~/$ROOT — the only directory sessions will be allowed to run in"
  fi

  mkdir -p -- "$HOME/${CONFIG%/*}"
  # Created under a 0077 umask rather than written and then chmod'd: between
  # those two there is a moment where a file that now does hold the shared
  # secret is readable by every account on this host. The chmod after it is not
  # redundant — it states the mode this file must have, where the umask only
  # arranges for it.
  #
  # Heredocs with a printf between them for each value, rather than one heredoc
  # with the two interpolated into it. The quoted delimiter is what keeps every
  # `$` and every `#` below literal, and unquoting it to reach two values would
  # expand the rest of the file along with them.
  (
    umask 077
    {
      cat <<'CONFIG'
# crswd configuration.
#
# Written once, by the installer. Nothing in this project writes it again — a
# re-install leaves whatever is here alone. This file is yours.
#
# The shared secret below was generated when this file was written. Everything
# else is commented out, so in every other respect it behaves exactly like no
# configuration file at all. Uncomment only what you mean to change. The full
# annotated list of every setting there is lives at
# https://github.com/nctiggy/claude-remote-session-webhook/blob/main/config.example
#
# This file holds a credential, and the daemon refuses to read a file that sets
# one at any mode but 0600. It was written that way. Keep it that way.
#
# Format: `key = value`, one per line. `#` starts a comment at the start of a
# line and nowhere else, because a shared secret may legitimately contain one.
# A key is its environment variable without the CRSW_ prefix, lower-cased. The
# environment still wins: flag, then environment, then this file, then the
# built-in default.

# The schema this file was written against. Leave it.
version = 1

# REQUIRED. The HMAC shared secret the API client signs with, at least 32
# bytes. Unset is a startup failure: an absent secret is an absent
# authentication layer, and a daemon that starts without one is worse than a
# daemon that does not start.
#
# This one was generated by the installer, from `openssl rand -hex 32`, and has
# never been printed — not to the terminal that ran the install, not into a log,
# not into the pipe from curl. This file is the only place it exists, which is
# where you read it from to configure a client.
#
# Replace it with one of your own whenever you like. Every client signing with
# the old one stops being able to reach the daemon at that moment, which is the
# whole of what rotating a shared secret means.
#
# A file that sets this must be mode 0600, which is how this one was written.
CONFIG
      printf 'shared_secret = %s\n' "$secret"
      cat <<'CONFIG'

# The blast radius, and the real containment control — keep it narrow.
# Colon-separated absolute paths; a session may only run in a directory one of
# them contains, and every entry must already exist.
#
# The installer wrote this one and created the directory. It is the daemon's
# own default, written out rather than left commented for two reasons: a
# default that only applies where the directory happens to exist is a daemon
# that refuses to boot on every host where it does not, and this line is the
# whole of what bounds a session running with the permission prompt turned off
# — which is a thing to be able to read, not to have to know.
#
# $HOME itself is never the default and is a poor choice: SSH keys, cloud
# credentials and browser profiles all live directly under it, which would make
# the allowlist decorative.
#
# The systemd unit sets CRSW_ALLOWED_ROOTS to this same directory, and the
# environment beats this file. Change what a session may reach and you have to
# change it in both places, or delete that line from the unit — an edit here
# alone is one that appears to have done nothing.
CONFIG
      printf 'allowed_roots = %s\n' "$HOME/$ROOT"
    } > "$HOME/$CONFIG"
  )
  chmod 0600 -- "$HOME/$CONFIG"
  # That one was generated, never which one. The line an operator reads here is
  # the line an operator pastes into an issue.
  say "wrote ~/$CONFIG (mode 0600, with a generated shared_secret and allowed_roots = ~/$ROOT)"
}

# What is left, said plainly, because nothing else is going to say it. Both of
# the settings the daemon has no usable default for are written now, so what
# remains is no longer a hand-edit somebody has to make before the service can
# come up. The unit is still printed rather than enabled: enabling one is a
# decision about somebody else's machine and nothing here has been asked to
# take it.
next_steps() {
  say ""
  say "Next: systemctl --user enable --now crswd"
  say ""
  say "shared_secret and allowed_roots are both set in ~/$CONFIG. Read it first —"
  say "allowed_roots is the only thing bounding what a session can reach."
  say ""
  say "Nothing was enabled and nothing is running: this installer starts no service."
}

main() {
  require_tools
  detect_platform
  say "detected $os/$arch"

  resolve_version
  say "downloading $version"

  workdir=$(mktemp -d)
  trap 'rm -rf -- "$workdir"' EXIT

  tarball="crswd_${version}_linux_${arch}.tar.gz"
  fetch "$tarball"
  fetch SHA256SUMS
  # Not optional. A release with no signature is refused, never installed on
  # the strength of a checksum that arrived from the same place as the bytes.
  fetch SHA256SUMS.sig
  fetch "$UNIT_ASSET"

  cd "$workdir"
  verify_signature
  verify_checksum "$tarball"
  verify_checksum "$UNIT_ASSET"

  # Only the member the release publishes, by name: an archive carrying extra
  # paths then cannot write anywhere this did not intend.
  mkdir -p unpacked
  tar -xzf "$tarball" -C unpacked crswd
  say "unpacked $tarball"

  place 0755 unpacked/crswd "$BINARY"
  place_unit
  write_config
  next_steps
}

main "$@"
